### ISSUE TITLE
como soluciono este error

### ISSUE THREAD

**Issue by colcrt** [oscoidi/Perceptron#3]
***entrenamiento numero 1 ***
Traceback (most recent call last):
  File "perceptron.py", line 143, in <module>
    Perceptron()
  File "perceptron.py", line 22, in __init__
    self.train() #entrenamos la red neuronal
  File "", line 66, in train
    self.readlines()
  File "perceptron.py", line 90, in readlines
    self.perceptron[0][3][k] = float(numero)
IndexError: list assignment index out of range

**Comment by oscoidi** [comment]
Buenas colcrt,

Cuando inicias el programa te pregunta el número de capas y el número de neuronas en cada capa. Lo importante es que la capa 0 tenga tantas neuronas como datos de entrada( en el ejemplo que he adjuntado 2 neuronas) y la última capa tiene que tener tantas neuronas como datos de salida(en este caso 1). 

Si el número de entradas y salidas no coincide con el número de neuronas salta un error de dimensión de matrices como el que te ha aparecido a ti.

Espero que te haya ayudado. Cualquier duda me comentas. Un saludo.
